language: cpp
sudo: required
dist: trusty
compiler: g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

os: linux

before_install: ./scripts/ci/dependencies.sh

script:
- mkdir server/build && cd server/build
- env CXX=g++-6 cmake .. && make && make test
