language: cpp
sudo: required
dist: trusty
compiler: g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libpqxx-dev
      - libboost-all-dev

os: linux
services: 
- postgresql

before_install: ./scripts/ci/dependencies.sh

before_script: 
- psql -c 'create database flat_mate;' -U postgres
- cp server/tests/include/db/PostgreConfigCI.h server/tests/include/db/PostgreConfig.h 

script:
- mkdir server/build && cd server/build
- env CXX=g++-6 cmake .. 
- make -j `nproc` 
- ctest -V
